# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: left_leg
  joint_model_group_pose: left_leg_start
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - al_joint
    - bl1_joint
    - cl1_joint
    - el1_joint
    - fl1_joint
    - hl_joint
    - il_joint
    - ar_joint
    - br1_joint
    - cr1_joint
    - er1_joint
    - fr1_joint
    - hr_joint
    - ir_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
left_leg_controller:
  type: position_controllers/JointPositionController
  joints:
    - al_joint
    - bl1_joint
    - cl1_joint
    - el1_joint
    - fl1_joint
    - hl_joint
    - il_joint
  gains:
    al_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    bl1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    cl1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    el1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fl1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    hl_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    il_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_leg_controller:
  type: position_controllers/JointPositionController
  joints:
    - ar_joint
    - br1_joint
    - cr1_joint
    - er1_joint
    - fr1_joint
    - hr_joint
    - ir_joint
  gains:
    ar_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    br1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    cr1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    er1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fr1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    hr_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ir_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1